name: "Build app"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      #- name: Harden Runner
      #  id: harden_runner
      #  uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      #  with:
      #    disable-sudo: true
      #    egress-policy: block
      #    allowed-endpoints: >
      #      github.com:443
      #      registry.npmjs.org:443

      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Use Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20.17.0'

      - name: "npm install"
        run: |
          cd ./src/public
          npm install

